"""auto publish and approval fields

Revision ID: c522a2195f06
Revises: b557745c7bef
Create Date: 2026-06-23 13:41:16.368253
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c522a2195f06'
down_revision: str | None = 'b557745c7bef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_page_id', sa.String(length=36), nullable=True))

    # server_default keeps the migration safe on tables that already hold rows.
    with op.batch_alter_table('scheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('content_type', sa.String(length=32), nullable=False, server_default='short_post')
        )
        batch_op.add_column(
            sa.Column('language', sa.String(length=8), nullable=False, server_default='en')
        )
        batch_op.add_column(
            sa.Column('auto_publish', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('require_approval', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('facebook_page_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_jobs', schema=None) as batch_op:
        batch_op.drop_column('facebook_page_id')
        batch_op.drop_column('require_approval')
        batch_op.drop_column('auto_publish')
        batch_op.drop_column('language')
        batch_op.drop_column('content_type')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('facebook_page_id')

    # ### end Alembic commands ###
